import type { Metadata } from "next";
import { Toaster } from "@starter/ui/src/components/toaster";
import "@starter/ui/styles/global.css";
import { Sidebar } from "@starter/web/components/sidebar/Sidebar.main";
import { TooltipProvider } from "@starter/ui/src/components/tooltip";

export const metadata: Metadata = {
  title: "Starter App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TooltipProvider>
        <body className="h-screen w-screen flex">
          <Sidebar />
          <main className="grow flex flex-col">{children}</main>
          <Toaster />
        </body>
      </TooltipProvider>
    </html>
  );
}
